const PDFDocument = require("pdfkit");

function addSectionTitle(doc, title) {
    doc.moveDown(0.8);
    doc
        .fillColor("#1e3a8a")
        .fontSize(14)
        .font("Helvetica-Bold")
        .text(title);
    doc
        .moveTo(doc.x, doc.y + 2)
        .lineTo(550, doc.y + 2)
        .strokeColor("#1e3a8a")
        .lineWidth(1)
        .stroke();
    doc.moveDown(0.5);
    doc.fillColor("#000000").font("Helvetica").fontSize(10);
}

function addRow(doc, label, value) {
    doc
        .font("Helvetica-Bold")
        .fontSize(10)
        .fillColor("#333333")
        .text(`${label}: `, { continued: true })
        .font("Helvetica")
        .fillColor("#000000")
        .text(value === undefined || value === null || value === "" ? "Unknown" : String(value));
}

function severityColor(level) {
    switch (level) {
        case "Critical": return "#dc2626";
        case "High": return "#f97316";
        case "Medium": return "#eab308";
        case "Low": return "#3b82f6";
        default: return "#64748b";
    }
}

function buildPdfBuffer(report, meta = {}) {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument({ margin: 50, size: "A4" });
            const chunks = [];

            doc.on("data", (chunk) => chunks.push(chunk));
            doc.on("end", () => resolve(Buffer.concat(chunks)));
            doc.on("error", (err) => reject(err));

            const scanId = meta.scanId || "N/A";
            const generatedBy = meta.generatedBy || "Guest User";
            const generatedAt = new Date();

            // ===== Cover / Header =====
            doc
                .fillColor("#1e3a8a")
                .fontSize(22)
                .font("Helvetica-Bold")
                .text("Sentinel AI", { align: "center" });

            doc
                .fontSize(13)
                .fillColor("#334155")
                .font("Helvetica")
                .text("Professional Security Assessment", { align: "center" });

            doc.moveDown(0.8);

            doc
                .fontSize(10)
                .fillColor("#555555")
                .text(`Generated: ${generatedAt.toLocaleString()}`, { align: "center" })
                .text(`Generated By: ${generatedBy}`, { align: "center" })
                .text(`Target: ${report.target || "Unknown"}`, { align: "center" })
                .text(`Scan ID: ${scanId}`, { align: "center" })
                .text(`Scan Time: ${report.responseTime || "Unknown"}`, { align: "center" });

            doc.moveDown(1);
            doc.moveTo(50, doc.y).lineTo(550, doc.y).strokeColor("#1e3a8a").lineWidth(1.5).stroke();

            // ===== Executive Summary =====
            addSectionTitle(doc, "Executive Summary");
            addRow(doc, "Overall Risk", report.risk);
            addRow(doc, "Security Score", `${report.score ?? "Unknown"} / 100`);
            addRow(doc, "Grade", report.grade);
            addRow(doc, "Website Status", report.httpStatus === 200 ? "Online" : `HTTP ${report.httpStatus}`);
            addRow(doc, "SSL Valid", report.ssl?.valid ? "Yes" : "No");

            // ===== Target Information =====
            addSectionTitle(doc, "Target Information");
            addRow(doc, "Target", report.target);
            addRow(doc, "Hostname", report.hostname);
            addRow(doc, "HTTP Status", report.httpStatus);
            addRow(doc, "Response Time", report.responseTime);

            // ===== Domain Information =====
            addSectionTitle(doc, "Domain Information");
            addRow(doc, "Registrar", report.domain?.registrar);
            addRow(doc, "Created", report.domain?.created);
            addRow(doc, "Updated", report.domain?.updated);
            addRow(doc, "Expires", report.domain?.expires);
            addRow(doc, "IP Address", report.domain?.ipAddress);
            addRow(doc, "Organisation", report.domain?.organisation);
            addRow(doc, "Country", report.domain?.country);
            addRow(doc, "ASN", report.domain?.asn);

            // ===== SSL Information =====
            addSectionTitle(doc, "SSL Information");
            addRow(doc, "Certificate", report.ssl?.valid ? "Valid" : "Invalid");
            addRow(doc, "Issuer", report.ssl?.issuer);
            addRow(doc, "Subject", report.ssl?.subject);
            addRow(doc, "Valid From", report.ssl?.validFrom);
            addRow(doc, "Valid To", report.ssl?.validTo);
            addRow(doc, "Days Remaining", report.ssl?.daysRemaining);
            addRow(doc, "TLS Version", report.ssl?.protocol);
            addRow(doc, "Cipher Suite", report.ssl?.cipher);

            // ===== Technology =====
            addSectionTitle(doc, "Technology Information");
            if (Array.isArray(report.technology) && report.technology.length > 0) {
                report.technology.forEach((t) => addRow(doc, t.name, t.value));
            } else {
                doc.text("No technology detected.");
            }

            // ===== Security Findings =====
            if (doc.y > 650) doc.addPage();
            addSectionTitle(doc, "Security Findings");

            const severityOrder = ["Critical", "High", "Medium", "Low", "Info"];
            const findings = Array.isArray(report.findings) ? report.findings : [];

            if (findings.length > 0) {
                severityOrder.forEach((level) => {
                    const group = findings.filter((f) => f.severity === level);
                    if (group.length === 0) return;

                    if (doc.y > 700) doc.addPage();

                    doc
                        .moveDown(0.4)
                        .font("Helvetica-Bold")
                        .fontSize(11)
                        .fillColor(severityColor(level))
                        .text(`${level} (${group.length})`);

                    doc.font("Helvetica").fontSize(10).fillColor("#000000");

                    group.forEach((finding) => {
                        if (doc.y > 720) doc.addPage();
                        doc.moveDown(0.3);
                        doc.font("Helvetica-Bold").text(`• ${finding.title || "Untitled finding"}`);
                        doc.font("Helvetica").fontSize(9).fillColor("#333333");
                        if (finding.description) doc.text(finding.description);
                        if (finding.impact) doc.text(`Impact: ${finding.impact}`);
                        if (finding.recommendation) doc.text(`Fix: ${finding.recommendation}`);
                        doc.fillColor("#000000").fontSize(10);
                    });
                });
            } else {
                doc.text("No findings available.");
            }

            // ===== Robots / Sitemap / Security.txt / Directory =====
            if (doc.y > 650) doc.addPage();
            addSectionTitle(doc, "Robots.txt");
            addRow(doc, "Found", report.robots?.exists ? "Yes" : "No");
            addRow(doc, "Allow Rules", report.robots?.allow?.length ?? 0);
            addRow(doc, "Disallow Rules", report.robots?.disallow?.length ?? 0);
            addRow(doc, "Sitemap Declared", report.robots?.sitemap || "Not declared");

            addSectionTitle(doc, "Sitemap");
            addRow(doc, "Found", report.sitemap?.exists ? "Yes" : "No");
            addRow(doc, "Total URLs", report.sitemap?.totalUrls ?? 0);
            addRow(doc, "Is Index", report.sitemap?.isIndex ? "Yes" : "No");

            addSectionTitle(doc, "Security.txt");
            addRow(doc, "Found", report.securitytxt?.exists ? "Yes" : "No");
            addRow(doc, "Contact", report.securitytxt?.contact);
            addRow(doc, "Policy", report.securitytxt?.policy);

            addSectionTitle(doc, "Directory Scan");
            addRow(doc, "Scanned", report.directory?.scanned ?? 0);
            addRow(doc, "Accessible", report.directory?.accessible ?? 0);
            addRow(doc, "Critical", report.directory?.critical ?? 0);
            addRow(doc, "High", report.directory?.high ?? 0);

            // ===== AI Analysis =====
            if (doc.y > 650) doc.addPage();
            addSectionTitle(doc, "AI Security Analysis");
            doc.fontSize(10).text(report.aiAnalysis || "AI analysis not available.", {
                width: 500,
                align: "left"
            });

            // ===== Footer =====
            doc.moveDown(2);
            doc
                .fontSize(8)
                .fillColor("#999999")
                .text("Generated by Sentinel AI Website Scanner", { align: "center" });

            doc.end();
        }
        catch (err) {
            reject(err);
        }
    });
}

async function generatePdfReport(report, res, meta = {}) {
    try {
        const buffer = await buildPdfBuffer(report, meta);

        res.setHeader("Content-Type", "application/pdf");
        res.setHeader(
            "Content-Disposition",
            `attachment; filename="sentinel-scan-${String(report.hostname || "report").replace(/[^a-z0-9.-]/gi, "_")}.pdf"`
        );
        res.setHeader("Content-Length", buffer.length);
        res.send(buffer);
    }
    catch (err) {
        console.log("PDF generation error:", err);
        if (!res.headersSent) {
            res.status(500).json({
                success: false,
                message: "PDF generation failed: " + err.message
            });
        }
    }
}

module.exports = generatePdfReport;
