services:

  db:
    image: postgres:16
    container_name: sentinel-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sentinel
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build:
      context: ./backend
    container_name: sentinel-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app


volumes:
  postgres_data: